language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm "CPAN::Meta" "CPAN::Meta::Requirements" "Data::Dump" "List::MoreUtils" "Module::Metadata" "Module::Signature" "MooX::Struct" "Moose" "Path::Iterator::Rule" "Path::Tiny" "RDF::DOAP::Project" "RDF::Trine" "RDF::TrineX::Functions" "RDF::TrineX::Parser::Pretdsl" "RDF::TrineX::Serializer::MockTurtleSoup" "Software::License" "Test::More" "Types::Path::Tiny" "Types::Standard" "namespace::autoclean"
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
